### ISSUE TITLE
Errors when using multiple GPUs

### ISSUE THREAD

**Issue by xinsu626** [JoaoLages/RATransformers#5]
Hello, I was trying to train the model on two GPUs using your example code but got the following errors. Could you please point me to the possible locations that caused this error? It looks like somewhere, the input to the model was moved to the second GPU. In trainer, the model and data are placed on the first GPU by default. Thank you!

```
Traceback (most recent call last):
  File "/home/python3.8/site-packages/transformers/trainer.py", line 2345, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/python3.8/site-packages/transformers/trainer.py", line 2377, in compute_loss
    outputs = model(**inputs)
  File "/home/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/python3.8/site-packages/ratransformers/__init__.py", line 193, in run
    return function(*args, **kwargs)
  File "/home/python3.8/site-packages/ratransformers/t5.py", line 114, in forward
    encoder_outputs = self.encoder(
  File "/home/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/python3.8/site-packages/ratransformers/t5.py", line 422, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/home/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/home/python3.8/site-packages/torch/nn/functional.py", line 2199, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select)
```

The example code I'm using is the following:

```
import json
from transformers import AutoModelForSeq2SeqLM
import ratransformers
import torch
from transformers import Seq2SeqTrainer, Seq2SeqTrainingArguments, EarlyStoppingCallback
from collections import defaultdict


class Text2SQLDataset(torch.utils.data.Dataset):
    def __init__(self, X, y, tokenizer, X_word_relations=None):
        self.X = X
        self.y = y
        self.X_word_relations = X_word_relations or [None] * len(X)
        self.tokenizer = tokenizer

    def __getitem__(self, index: int) -> dict:
        source = self.tokenizer(self.X[index], padding='max_length', input_relations=self.X_word_relations[index],
                                return_tensors="pt")
        target = self.tokenizer(self.y[index], padding='max_length', input_relations=None, return_tensors="pt")

        source_ids = source["input_ids"].squeeze()
        source_input_relations = source["input_relations"].squeeze()
        target_ids = target["input_ids"].squeeze()
        target_ids[target_ids == 0] = -100

        src_mask = source["attention_mask"].squeeze()
        target_mask = target["attention_mask"].squeeze()

        return {
            "input_ids": source_ids.to('cuda:0'),
            "attention_mask": src_mask.to('cuda:0'),
            "label": target_ids.to('cuda:0'),
            "decoder_attention_mask": target_mask.to('cuda:0'),
            'input_relations': source_input_relations.to('cuda:0')
        }

    def __len__(self):
        return len(self.X)


def get_processed_data(raw_data):
    X, y, X_word_relations = [], [], []
    n_skip = 0
    for d in raw_data:
        input_text = d['question'] + f" | {d['db_id']}"

        word_relations = defaultdict(dict)

        table_span, table_i = None, None
        for i, c_name in tables[d['db_id']]['column_names_original']:
            if i < 0: continue
            if table_i != i:
                table_i = i
                table_span = (
                    len(input_text + ' | '),
                    len(input_text + ' | ') + len(tables[d['db_id']]['table_names_original'][i]))
                input_text += f" | {tables[d['db_id']]['table_names_original'][i]} : "

                c_span = (len(input_text), len(input_text) + len(c_name))
                input_text += c_name

            else:
                c_span = (len(input_text + ', '), len(input_text + ', ') + len(c_name))
                input_text += f', {c_name}'

            word_relations[table_span][c_span] = 'table_column_link'
            word_relations[c_span][table_span] = 'column_table_link'

        if len(input_text.split()) > 200:
            # Skipped sample with too long input
            n_skip += 1
            continue

        X.append(input_text.lower())
        y.append((d['db_id'] + ' | ' + d['query']).lower())
        X_word_relations.append(word_relations)

    return X, y, X_word_relations, n_skip


with open('spider/tables.json') as fp:
    tables = {t['db_id']: t for t in json.load(fp)}

with open('spider/train_spider.json') as fp:
    train_data = json.load(fp)

with open('spider/train_others.json') as fp:
    train_data += json.load(fp)

with open('spider/dev.json') as fp:
    test_data = json.load(fp)

train_X, train_y, train_X_word_relations, n_skip = get_processed_data(train_data)
print("Train:", len(train_X), f" Skipped {n_skip} samples with too long input.")
test_X, test_y, test_X_word_relations, n_skip = get_processed_data(test_data)
print("Test:", len(test_X), f" Skipped {n_skip} samples with too long input.")

ratransformer = ratransformers.RATransformer(
    'tscholak/1zha5ono',
    relation_kinds=['table_column_link', 'column_table_link'],
    model_cls=AutoModelForSeq2SeqLM
)
model = ratransformer.model
tokenizer = ratransformer.tokenizer
# Get datasets with word relations
train_d = Text2SQLDataset(train_X, train_y, tokenizer, train_X_word_relations)
val_d = Text2SQLDataset(test_X, test_y, tokenizer, test_X_word_relations)

# Get datasets without word relations
train_d_without_relations = Text2SQLDataset(train_X, train_y, tokenizer)
val_d_without_relations = Text2SQLDataset(test_X, test_y, tokenizer)

# Set training arguments
training_args = Seq2SeqTrainingArguments(
    output_dir='checkpoints',
    per_device_train_batch_size=1,
    gradient_accumulation_steps=2,
    per_device_eval_batch_size=4,
    max_steps=100000,
    eval_steps=1000,
    seed=42,
    save_total_limit=1,
    predict_with_generate=True,
)

# Set trainer
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=train_d,
    eval_dataset=val_d,
    tokenizer=tokenizer,
)

# # get performance before training
# trainer.evaluate()

# train until early stopping
trainer.train()

# get performance after training
trainer.evaluate()

# Save model
trainer.save_model('ra-tscholak/1zha5ono')

# Reload model again
ratransformer = ratransformers.RATransformer(
    'ra-tscholak/1zha5ono',
    relation_kinds=['table_column_link', 'column_table_link'],
    alias_model_name='t5'
)
model = ratransformer.model
tokenizer = ratransformer.tokenizer

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=train_d,
    eval_dataset=val_d,
    tokenizer=tokenizer,
    callbacks=[EarlyStoppingCallback()]
)
trainer.evaluate()

```

**Comment by xinsu626** [comment]
Update: 
- This error only happens when using the data parallel.
- I also noticed that RATLongT5 is super slow and cannot scale to long sequences.

**Comment by JoaoLages** [comment]
Thanks for submitting the issue 👍 

> * This error only happens when using the data parallel.

How did you deactivate data parallelism in the previous code snippet?

> * I also noticed that RATLongT5 is super slow and cannot scale to long sequences.

Yes, that's expected, unfortunately. Did you try tglobal or local attention? local attention should work faster

**Comment by xinsu626** [comment]
@JoaoLages Thanks for your reply and helps!

> How did you deactivate data parallelism in the previous code snippet?

I used distributed training instead of data parallel: `python -m torch.distributed.launch --nproc_per_node=${NUM_DEVICE} main.py`

> Yes, that's expected, unfortunately. Did you try tglobal or local attention? local attention should work faster

Yes, I tried both, but they were both very slow. So I was wondering if it might be possible to specify the use of RAT in certain layers to reduce the computational cost.

**Comment by JoaoLages** [comment]
> So I was wondering if it might be possible to specify the use of RAT in certain layers to reduce the computational cost.

It is, but it requires a few changes. You can try to hardcode locally your ratransformers [in here](https://github.com/JoaoLages/RATransformers/blob/f258c1cd0dab18132389928b33f0cf9ba4f325d8/src/ratransformers/longt5.py#L22) to just apply RAT in some specific `module_name`

Regarding the data parallelism problem, I think the error is because I define [the embedding layer for RAT](https://github.com/JoaoLages/RATransformers/blob/f258c1cd0dab18132389928b33f0cf9ba4f325d8/src/ratransformers/__init__.py#L55) and then it doesnt match the device where the rest of the model is. I'm not sure how to fix that now, but it should be simple 🤔

**Comment by xinsu626** [comment]
> It is, but it requires a few changes. You can try to hardcode locally your ratransformers [in here](https://github.com/JoaoLages/RATransformers/blob/f258c1cd0dab18132389928b33f0cf9ba4f325d8/src/ratransformers/longt5.py#L22) to just apply RAT in some specific module_name

Thanks. It looks like longt5 is still slow even after I stopped using all the RATs. The job that was running for 10 hours for vanilla longt5 is now running for 300 hours. Here is my code to stop all the RATs.
```
def change_longt5_module_and_get_relational_emb_dim(module_name: str, module: nn.Module) -> Optional[int]:
    relational_embedding_dim = None
    matched = re.match(r"encoder.block.(\d+).*", module_name)
    if matched:
        layer_num = matched.group(1)
        if int(layer_num) >= 0:
            return
    if 'encoder' in module_name and 'decoder' not in module_name and isinstance(module, LongT5Attention):
        module.forward = MethodType(RelationalLongT5Attention.forward, module)
        relational_embedding_dim = module.inner_dim // module.n_heads
    if 'encoder' in module_name and 'decoder' not in module_name and isinstance(module, LongT5LocalAttention):
        module.forward = MethodType(RelationalLongT5LocalAttention.forward, module)
        relational_embedding_dim = module.inner_dim // module.n_heads
    if 'encoder' in module_name and 'decoder' not in module_name and isinstance(module, LongT5TransientGlobalAttention):
        module.forward = MethodType(RelationalLongT5TransientGlobalAttention.forward, module)
        relational_embedding_dim = module.inner_dim // module.n_heads
    elif isinstance(module, LongT5Stack):
        module.forward = MethodType(RelationalLongT5Stack.forward, module)
    elif isinstance(module, LongT5ForConditionalGeneration):
        module.forward = MethodType(RelationalLongT5ForConditionalGeneration.forward, module)
    elif isinstance(module, LongT5Model):
        module.forward = MethodType(RelationalLongT5Model.forward, module)
    elif isinstance(module, LongT5EncoderModel):
        module.forward = MethodType(RelationalLongT5EncoderModel.forward, module)
    elif isinstance(module, LongT5Block):
        module.forward = MethodType(RelationalLongT5Block.forward, module)
    elif isinstance(module, LongT5LayerCrossAttention):
        module.forward = MethodType(RelationalLongT5LayerCrossAttention.forward, module)
    elif isinstance(module, LongT5LayerSelfAttention):
        module.forward = MethodType(RelationalLongT5LayerSelfAttention.forward, module)
    elif isinstance(module, LongT5LayerLocalSelfAttention):
        module.forward = MethodType(RelationalLongT5LayerLocalSelfAttention.forward, module)
    elif isinstance(module, LongT5LayerTransientGlobalSelfAttention):
        module.forward = MethodType(RelationalLongT5LayerTransientGlobalSelfAttention.forward, module)

    return relational_embedding_dim
```

**Comment by JoaoLages** [comment]
That should stop the addition of RAT layers,  yes. You can `return` right at the beginning of the function to make sure that no RAT layers are added.
Did you try to run LongT5 from `transformers` instead of `ratransformers`+(your code to stop adding RAT layers) to see the difference? The tokenizer in transformers can also be a bit slower, but the rest should be 100% the same 🤔
